import { DEFAULT_DISTRIBUTION } from './rarity';

export const CASES = [
  {
    id: 'genin_case',
    name: 'Кейс Генина',
    price: 100,
    type: 'Skin',
    image: '📦',
    color: '#A259F7',
    rarityDistribution: { Consumer: 0.85, Industrial: 0.13, Restricted: 0.018, Classified: 0.002, Covert: 0, Legendary: 0 },
  },
  {
    id: 'chunin_case',
    name: 'Кейс Чунина',
    price: 300,
    type: 'Skin',
    image: '🎁',
    color: '#FF9900',
    rarityDistribution: { Consumer: 0.75, Industrial: 0.18, Restricted: 0.05, Classified: 0.017, Covert: 0.003, Legendary: 0 },
  },
  {
    id: 'konoha_case',
    name: 'Кейс Конохи',
    price: 500,
    type: 'Skin',
    image: '🍃',
    color: '#BFFF00',
    rarityDistribution: DEFAULT_DISTRIBUTION,
  },
  {
    id: 'suna_case',
    name: 'Кейс Суны',
    price: 750,
    type: 'Skin',
    image: '🏜️',
    color: '#FFD700',
    rarityDistribution: { Consumer: 0.70, Industrial: 0.20, Restricted: 0.07, Classified: 0.02, Covert: 0.009, Legendary: 0.001 },
  },
  {
    id: 'sharingan_case',
    name: 'Кейс Шарингана',
    price: 1000,
    type: 'Skin',
    image: '👁️',
    color: '#FF3F3F',
    rarityDistribution: { Consumer: 0.60, Industrial: 0.25, Restricted: 0.10, Classified: 0.035, Covert: 0.0145, Legendary: 0.0005 },
  },
  {
    id: 'akatsuki_case',
    name: 'Кейс Акацуки',
    price: 1500,
    type: 'Skin',
    image: '☁️',
    color: '#A259F7',
    rarityDistribution: { Consumer: 0.55, Industrial: 0.25, Restricted: 0.13, Classified: 0.05, Covert: 0.019, Legendary: 0.001 },
  },
  {
    id: 'jounin_case',
    name: 'Кейс Джонина',
    price: 2000,
    type: 'Skin',
    image: '⚡',
    color: '#00CCFF',
    rarityDistribution: { Consumer: 0.50, Industrial: 0.25, Restricted: 0.15, Classified: 0.07, Covert: 0.028, Legendary: 0.002 },
  },
  {
    id: 'rinnegan_case',
    name: 'Кейс Риннегана',
    price: 3000,
    type: 'Skin',
    image: '🌀',
    color: '#A259F7',
    rarityDistribution: { Consumer: 0.40, Industrial: 0.28, Restricted: 0.20, Classified: 0.09, Covert: 0.027, Legendary: 0.003 },
  },
  {
    id: 'bijuu_case',
    name: 'Кейс Биджу',
    price: 4000,
    type: 'Skin',
    image: '🦊',
    color: '#FF9900',
    rarityDistribution: { Consumer: 0.30, Industrial: 0.30, Restricted: 0.24, Classified: 0.12, Covert: 0.036, Legendary: 0.004 },
  },
  {
    id: 'hokage_case',
    name: 'Кейс Хокаге',
    price: 5000,
    type: 'Knife',
    image: '👑',
    color: '#FFD700',
    rarityDistribution: { Consumer: 0.20, Industrial: 0.30, Restricted: 0.28, Classified: 0.15, Covert: 0.065, Legendary: 0.005 },
  },
];

export const getCaseById = (id) => CASES.find((c) => c.id === id);
